/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Memory {
  'id' : string,
  'title' : string,
  'content' : string,
  'date' : string,
}
export interface Message {
  'content' : string,
  'sender' : string,
  'timestamp' : string,
}
export interface Quote { 'text' : string, 'author' : string }
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addFunFact' : ActorMethod<[string], undefined>,
  'addMemory' : ActorMethod<[string, string, string, string], undefined>,
  'addMessage' : ActorMethod<[string, string, string], undefined>,
  'addQuote' : ActorMethod<[string, string], undefined>,
  'getAllMessages' : ActorMethod<[], Array<Message>>,
  'getConversation' : ActorMethod<[], Array<Message>>,
  'getMemories' : ActorMethod<[], Array<Memory>>,
  'getRandomFunFact' : ActorMethod<[], string>,
  'getRandomQuote' : ActorMethod<[], Quote>,
  'isCodeCorrect' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];